# #36. Why doesn't C++ have a `finally` construct? (Part 5)

Now here's **Busy** in action in a simpler version of **XDividedByY**.

```cpp
float XDividedByY(float x, float y) {
    Busy b;
    if (y == 0.f) throw std::exception();
    return x / y;
};
```

That first line (`Busy b;`) just creates an instance of **Busy**. It's an automatic variable, remember, so it's automatically destroyed as soon as **XDividedByY** exits (exits for whatever reason; exception or not). So with that change the internal state of our program is correct again, whether or not that exception is thrown.

And with that we've solved all of the exception safety issues that we had with the vintage code listing in [#30. Why doesn't C++ have a `finally` construct? (Part 2)](030.md).

In programming, the term *finalization* is associated with the end of the useful lifetime of an object. In C++, we know exactly when finalization will occur (at the end of a scope for an automatic variable; or when `delete` is called for a pointer variable). Knowing exactly when finalization will occur is called *deterministic finalization*, and it's the feature of C++ that lets us do elegant things such as *resource acquisition is initialization* (RAII). In C#, we don't know exactly when finalization will occur, if at all, but we can still use the [dispose pattern](https://docs.microsoft.com/dotnet/standard/garbage-collection/implementing-dispose) to signal an object to release its unmanaged resources in a somewhat predictable manner.

|Prev|Next|Contents|
|-|-|-|
|[#35. Why doesn't C++ have a `finally` construct? (Part 4)](035.md)|[#37. Pop quiz!](037.md)|[Bite-sized C++](../README.md)|
